
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sfluentd
  namespace: default
  labels:
    k8s-app: sfluentd
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: sfluentd        
  template:
    metadata:
      labels:
        k8s-app: sfluentd
        version: v1
    spec:
      serviceAccount: sfluentd
      serviceAccountName: sfluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: sfluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-syslog
        env:
          - name:  SYSLOG_HOST
            value: "(your system IP)"
          - name:  SYSLOG_PORT
            value: "514"
          - name:  SYSLOG_PROTOCOL
            value: "udp"            
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
